version: '3'

services:
  web:
    image: jitsi/web
    ports:
      - '8000:80'
      - '8443:443'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/jitsi-meet.cfg/web:/config
      - ${WEBAPP_STORAGE_HOME}/jitsi-meet.cfg/web/letsencrypt:/etc/letsencrypt
      - ${WEBAPP_STORAGE_HOME}/jitsi-meet.cfg/transcripts:/usr/share/jitsi-meet/transcripts
    environment:
      - ENABLE_AUTH
      - ENABLE_GUESTS
      - ENABLE_LETSENCRYPT
      - ENABLE_HTTP_REDIRECT
      - ENABLE_TRANSCRIPTIONS
      - DISABLE_HTTPS
      - JICOFO_AUTH_USER
      - LETSENCRYPT_DOMAIN
      - LETSENCRYPT_EMAIL
      - PUBLIC_URL
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_BOSH_URL_BASE
      - XMPP_GUEST_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_RECORDER_DOMAIN
      - ETHERPAD_URL_BASE
      - TZ
      - ENABLE_RECORDING
    networks:
      meet.jitsi:
        aliases:
          - ${XMPP_DOMAIN}

  prosody:
    image: jitsi/prosody
    expose:
      - '5222'
      - '5347'
      - '5280'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/jitsi-meet.cfg/prosody:/config
    environment:
      - AUTH_TYPE
      - ENABLE_AUTH
      - ENABLE_GUESTS
      - GLOBAL_MODULES
      - GLOBAL_CONFIG
      - JWT_ASAP_KEYSERVER
      - JWT_ALLOW_EMPTY
      - JWT_AUTH_TYPE
      - JWT_TOKEN_AUTH_MODULE
      - LOG_LEVEL
      - TZ
    networks:
      meet.jitsi:
        aliases:
          - ${XMPP_SERVER}

  jicofo:
    image: jitsi/jicofo
    volumes:
      - ${WEBAPP_STORAGE_HOME}/jitsi-meet.cfg/jicofo:/config
    environment:
      - ENABLE_AUTH
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_SERVER
      - JVB_BREWERY_MUC
      - JIGASI_BREWERY_MUC
      - JIBRI_BREWERY_MUC
      - JIBRI_PENDING_TIMEOUT
      - TZ
    depends_on:
      - prosody
    networks:
      meet.jitsi:

  jvb:
    image: jitsi/jvb
    ports:
      - '10000:10000/udp'
      - '4443:4443'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/jitsi-meet.cfg/jvb:/config
    environment:
      - DOCKER_HOST_ADDRESS
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_SERVER
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JVB_BREWERY_MUC
      - JVB_PORT
      - JVB_TCP_HARVESTER_DISABLED
      - JVB_TCP_PORT
      - JVB_STUN_SERVERS
      - JVB_ENABLE_APIS
      - TZ
    depends_on:
      - prosody
    networks:
      meet.jitsi:

networks:
  meet.jitsi:
